services:
  db:
    image: postgres:15.8-alpine3.20
    ports:
      - 5433:5432
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=fctubedb
    

  pgadmin:
    image: dpage/pgadmin4:8.11.0
    ports:
      - 5051:80
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@user.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    depends_on:
      - db